networks:
  dev:
    driver: bridge

volumes:
  db-data: {}
  redis-data: {}

services:
  api:
    build: .
    container_name: QuiLaCarne-api
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-postgres}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_MAIL_HOST=mailpit
      - SPRING_MAIL_PORT=1025
      - JWT_SECRET_KEY=${API_JWT_SECRET_KEY}
      - JWT_EXPIRATION=${API_JWT_EXPIRATION:-86400000}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dev

  postgres:
    image: postgres:18-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - dev
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:v1.27.9
    container_name: mailpit-dev
    ports:
      - "${MAILPIT_UI_PORT:-8025}:8025"
      - "1025:1025"
    networks:
      - dev
    restart: unless-stopped

  redis:
    image: redis:8.2-alpine
    container_name: redis-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev
    restart: unless-stopped

  test:
    container_name: test
    image: eclipse-temurin:21-jdk-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-restaurant}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_MAIL_HOST=mailpit
      - SPRING_MAIL_PORT=1025
      - JWT_SECRET_KEY=${API_JWT_SECRET_KEY}
      - JWT_EXPIRATION=${API_JWT_EXPIRATION:-86400000}
    command: ./gradlew test --no-daemon
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
