networks:
  dev:
    driver: bridge

volumes:
  loki-data: { }

services:
  api:
    build: .
    container_name: QuiLaCarne-api
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_CONNECTION_STRING}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=postgres
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST:-redis}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT:-6379}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_DATA_REDIS_SSL=${REDIS_SSL}
      - SPRING_MAIL_HOST=mailpit
      - SPRING_MAIL_PORT=1025
      - JWT_SECRET_KEY=${API_JWT_SECRET_KEY}
      - JWT_EXPIRATION=${API_JWT_EXPIRATION:-86400000}
      - FRONTEND_URL=${FRONTEND_URL}
      - API_SHOW_SQL=${API_SHOW_SQL}
      - API_FORMAT_SQL=${API_FORMAT_SQL}
      - API_LOGGING_LEVEL=${API_LOGGING_LEVEL}
      - TZ=UTC
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_LOGIN=${S3_ACCESS_LOGIN}
      - S3_SECRET_PASSWORD=${S3_SECRET_PASSWORD}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - SPRING_MAIL_HOST=${SMTP_HOST:-smtp-relay.brevo.com}
      - SPRING_MAIL_PORT=${SMTP_PORT:-587}
      - SPRING_MAIL_USERNAME=${SMTP_USERNAME}
      - SPRING_MAIL_PASSWORD=${SMTP_PASSWORD}
      - SPRING_EMAIL_USERNAME=${API_EMAIL_FROM}
      - API_EMAIL_FROM=${API_EMAIL_FROM}
    networks:
      - dev
