spring.application.name=QuiLaCarne_API
# Web Adress
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173}
# JWT Configuration
application.security.jwt.secret-key=${API_JWT_SECRET_KEY:mySecretKeyForJwtTokenGenerationPleaseChangeInProduction123456789}
application.security.jwt.expiration=${API_JWT_EXPIRATION:3600000}
# Database Configuration
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${API_SHOW_SQL:false}
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.main.lazy-initialization=true
# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL:false}
# Mail Configuration
spring.mail.host=${SMTP_HOST:smtp-relay.brevo.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
app.mail.from=${API_EMAIL_FROM:no-replay@quilacarne.pl}
spring.mail.properties.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true
# Google OAuth2
application.security.google.client-id=${GOOGLE_CLIENT_ID:}
# S3
application.storage.s3.endpoint=${S3_ENDPOINT}
application.storage.s3.public-endpoint=${S3_PUBLIC_ENDPOINT:http://localhost:9000}
application.storage.s3.region=${S3_REGION}
application.storage.s3.access-key=${S3_ACCESS_LOGIN}
application.storage.s3.secret-key=${S3_SECRET_PASSWORD}
application.storage.s3.bucket-name=${S3_BUCKET_NAME}
# Logs
spring.jpa.properties.hibernate.format_sql=${API_FORMAT_SQL:false}
logging.level.com.example.restaurant=${API_LOGGING_LEVEL:DEBUG}
#management.endpoints.web.exposure.include=health,info,metrics,prometheus
#management.endpoint.health.show-details=always
#management.endpoint.prometheus.enabled=true
#management.prometheus.metrics.export.enabled=true
#management.metrics.tags.application=${spring.application.name}
#management.metrics.tags.env=dev
# Swagger
springdoc.api-docs.enabled=${API_SWAGGER_ENABLED:false}
springdoc.swagger-ui.enabled=${API_SWAGGER_ENABLED:false}