spring.application.name=QuiLaCarne_API

# Web Adress
app.url=

# JWT Configuration
application.security.jwt.secret-key=${API_JWT_SECRET_KEY:mySecretKeyForJwtTokenGenerationPleaseChangeInProduction123456789}
application.security.jwt.expiration=${API_JWT_EXPIRATION:86400000}

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Mail Configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.smtp.auth=false
spring.mail.properties.smtp.starttls.enable=false