name: CI Pipeline

on:
  push:
    branches: ["main", "stage"]
  pull_request:
    branches: ["main", "stage"]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      API_JWT_SECRET_KEY: ${{ secrets.API_JWT_SECRET_KEY }}
      API_JWT_EXPIRATION: 3600000
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      API_PORT: 8080
      POSTGRES_PORT: 5432
      REDIS_PORT: 6379
      MAILPIT_UI_PORT: 8025

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup java nad gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run:  ./gradlew test --no-daemon
